Vagrant.configure("2") do |config|

  # Define the VM
  config.vm.define "vm_nginx" do |vm_nginx|
    vm_nginx.vm.box = "generic/ubuntu2204"
    vm_nginx.vm.hostname = "vm1"
    vm_nginx.vm.network "private_network", ip: "192.168.56.101"
    vm_nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provisioning script
    vm_nginx.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx

      # Start NGINX service
      sudo systemctl start nginx

      # Enable NGINX to start on boot
      sudo systemctl enable nginx
    SHELL

    # Port forwarding configuration
    vm_nginx.vm.network "forwarded_port", guest: 80, host: 8080
  end

end
