version: '3.7'
services:
  nginx-lua:
    image: openresty/openresty:1.19.9.1-3-focal
    #    command: sh -c "cd /usr/local/openresty/bin && opm get antonheryanto/lua-resty-post && chmod -R 777 /var/www/html"
    restart: always
    ports:
      - "8088:80"
      - "344:443"
    volumes:
      - /mnt/file_server:/var/www/html
      - ./my_code.lua:/usr/local/lib/lua/5.1/my_code.lua:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ['CMD', 'curl --fail http://localhost/ || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3